[package]
name = "hvdos.rs"
version = "0.2.0"
authors = ["Satoshi Moriai <satoshi.moriai@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
cc = "1.0"
rustc_tools_util = "0.1"

[dependencies]
xhypervisor = "0.0.12"
rustc_tools_util = "0.1"
getopts = "0.2"
colored = "1.9"
